apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: nginx-
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.5-alpine
        ports:
          - name: web
            containerPort: 80
        volumeMounts:
          - name: nginx-vol-1
            mountPath: /usr/share/nginx/html
          - name: nginx-vol-2
            mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-vol-1
        persistentVolumeClaim:
          claimName: nginx-vol-1-claim
      - name: nginx-vol-2
        configMap:
          name: nginx-configmap
